### PR TITLE
Added Bitcore (BTX)

### PR DESCRIPTION
**Pull request by dArkjON**
Hi @nomiddleman and @rgostic,
here a contribution for Bitcore BTX.

Greetings
Jon

Website: bitcore.cc

SLIP44=160
COIN_P2PKH_VERSION=3
COIN_P2SH_VERSION=125

### CODE REVIEW

**Comment by nomiddleman** [comment]
Need to verify the insight API works somehow. Also as for ordering, everything is added at the end of the list (in the order they are added) except for insight API getTransactions and the readme.txt list (ordered by symbol). Can you add our logo to your site under wallets/payment processors?

**Comment by dArkjON** [comment]
Hey,
Just drop me your Bitcore Wallet and I’ll send you some coins for testing. I made a Order on my Test WordPress and also the Payment was catched.

We will release a news the next Week for Payment Plugins on WordPress and it would be nice to have you onboard 😎👍

**Comment by nomiddleman** [comment]
2Ensi6pSDXJWLUdBET9f38QT7CRktRT6TN

**Comment by dArkjON** [comment]
> 2Ensi6pSDXJWLUdBET9f38QT7CRktRT6TN

57500d592947680d58cad16239c765476eaed6892c340864d0748fb4f78f490d

**Comment by dArkjON** [comment]
> Also as for ordering, everything is added at the end of the list (in the order they are added) except for insight API getTransactions and the readme.txt list (ordered by symbol). ... Also remove the versions as that's for wordpress and we might have other updates before we push to the wordpress repo.

* Version 2.4.1 removed
* Redesigned code according to specification

**Comment by nomiddleman** [comment]
Last thing is a 25x25 logo for a white background.

**Comment by nomiddleman** [comment]
Looks like HD Address generation is not working.

**Comment by dArkjON** [comment]
works great for me, you made any test for the API, Founds doesnt move yet...

**Comment by nomiddleman** [comment]
What address can I send the BTX back to?

**Comment by dArkjON** [comment]
Please keep it as small donation :+1: 
Is there any ETA for a new Wordpress push and readme update ?

**Comment by nomiddleman** [comment]
Thank you! Next release coming soon.

**Pull request merged**
